[package]
name = "lcode"
version = "0.5.4"
edition = "2021"
authors = ["saying121 <xzsxzy@qq.com>"]
description = "Mediocre leetcode cli client."
# documentation = "https://github.com/saying121/leetcode-cn-en-cli/blob/main/README.md"
homepage = "https://github.com/saying121/leetcode-cn-en-cli"
repository = "https://github.com/saying121/leetcode-cn-en-cli"
license-file = "./LICENSE"
readme = "./README.md"
keywords = ["cli", "leetcode"]
categories = [""]
exclude = ["sample/"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# async
tokio = { version = "^1", features = ["full"] }
futures = { version = "^0.3" }

reqwest = { version = "^0", features = ["gzip", "json"] }
miette = { version = "^5", features = ["fancy"] }

# Serialize
serde = { version = "^1", features = ["derive"] }
serde_json = { version = "^1" }
toml = { version = "^0" }
ini = "^1"

dirs = { version = "^5" }
colored = { version = "^2" }

# database
sea-orm = { version = "^0.12", features = [
    "sqlx-sqlite",
    "runtime-async-std-native-tls",
] }

# render
html2text = { version = "0.6.0" }
pulldown-cmark-mdcat = { version = "^2", features = [] }
pulldown-cmark = "0.9.3"
syntect = { version = "^5", default-features = false, features = [
    "regex-fancy",
    "default-syntaxes",
] }

regex = { version = "1.9.3" }
scraper = { version = "0.17.1" }

# log
tracing = { version = "0.1.37" }
tracing-appender = { version = "0.2.2" }
tracing-error = { version = "0.2.0" }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

simsearch = { version = "0.2.4" }
inquire = { version = "0.6.2" }
atoi = { version = "^2" }
unicode-width = { version = "0.1.10" }

tabled = { version = "0.14.0" }
clap = { version = "^4", features = ["derive"] }

# tui
ratatui = { version = "0.23.0" }
crossterm = { version = "0.26.1" }
# tui-term = { version = "0.1.2" }
tui-textarea = { git = "https://github.com/saying121/tui-textarea", rev = "d7193217468", default-features = false, features = [
    "ratatui-crossterm",
] }
open = { version = "^5" }
# tui-logger = { version = "0.9.5" }

rayon = { version = "^1" }

# decrypt cookies
openssl = { version = "0.10.56" }
secret-service = { version = "^3", features = ["rt-tokio-crypto-rust"] }

[profile.release]
opt-level = 3
lto = true
