[package]
name = "lcode"
version = "0.5.9"
edition = "2021"
authors = ["saying121 <saying121@outlook.com>"]
description = "An application of terminal write leetcode.一个终端刷力扣的应用"
# documentation = "https://github.com/saying121/leetcode-cn-en-cli/blob/main/README.md"
documentation = "https://docs.rs/lcode"
homepage = "https://github.com/saying121/leetcode-cn-en-cli"
repository = "https://github.com/saying121/leetcode-cn-en-cli"
license-file = "./LICENSE"
readme = "./README.md"
keywords = ["cli", "leetcode", "tui", "terminal", "algorithms"]
categories = ["algorithms", "command-line-utilities", "asynchronous"]
exclude = [".github", "sample/"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# async
tokio = { version = "^1", features = ["full"] }
futures = { version = "^0.3" }

reqwest = { version = "^0", features = ["gzip", "json"] }
miette = { version = "^5", features = ["fancy"] }

# Serialize
serde = { version = "^1", features = ["derive"] }
serde_json = { version = "^1" }
toml = { version = "^0" }
ini = "^1"

dirs = { version = "^5" }
colored = { version = "^2" }

# database
sea-orm = { version = "^0.12", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
] }

# render
html2text = { version = "0.6.0" }
pulldown-cmark-mdcat = { version = "^2", features = [] }
pulldown-cmark = "0.9.3"
syntect = { version = "^5", default-features = false, features = [
    "regex-fancy",
    "default-syntaxes",
] }

regex = { version = "1.9.3" }
scraper = { version = "^0" }

# log
tracing = { version = "0.1.37" }
tracing-appender = { version = "0.2.2" }
tracing-error = { version = "0.2.0" }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

# nucleo = "0.2.1"
simsearch = { version = "0.2.4" }
inquire = { version = "0.6.2" }
atoi = { version = "^2" }
unicode-width = { version = "0.1.10" }

tabled = { version = "0.14.0" }
clap = { version = "^4", features = ["derive"] }

# tui
ratatui = { version = "0.24.0" }
crossterm = { version = "0.27.0" }
# tui-term = { version = "0.1.2" }
tui-textarea = { version = "0.3.0" }
# tui-logger = { version = "0.9.5" }
open = { version = "^5" }

rayon = { version = "^1" }

# decrypt cookies
openssl = { version = "0.10.56" }
secret-service = { version = "^3", features = ["rt-tokio-crypto-rust"] }

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
panic = "abort"
