[package]
name = "leetcode-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
reqwest = { version = "0.11.18", features = ["gzip", "json"] }
miette = { version = "5.10.0", features = ["fancy"] }
serde = { version = "1.0.173", features = ["derive"] }
serde_json = { version = "1.0.103" }
toml = { version = "0.7.6" }
dirs = { version = "5.0.1" }
tokio-test = { version = "0.4.2" }
html2text = { version = "0.6.0" }
pulldown-cmark-mdcat = { version = "2.0.3", features = [] }
pulldown-cmark = "0.9.3"
syntect = { version = "5.0.0", default-features = false, features = [
    "regex-fancy",
    "default-syntaxes",
] }
colored = { version = "2.0.4" }
sea-orm = { version = "0.12.1", features = [
    "sqlx-sqlite",
    "runtime-async-std-native-tls",
] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[profile.release]
opt-level = 3
lto = true
