[target.aarch64-unknown-linux-gnu]
# when use `vendored` feature not need install
# pre-build = [
#     "apt update && apt install -y libdbus-1-dev pkg-config",
# ]
[target.armv7-unknown-linux-gnueabihf]
# image = "rustcross:dbus-armhf"

[build.env]
# passthrough = [
# 	"RUSTFLAGS",
# ]
