[formatting]
align_entries         = true
align_comments        = true
array_trailing_comma  = true
array_auto_expand     = true
array_auto_collapse   = true
compact_arrays        = true
compact_inline_tables = false
inline_table_expa     = true
compact_entries       = false
column_width          = 120
indent_tables         = false
indent_entries        = false
trailing_newline      = true
reorder_keys          = false
reorder_arrays        = false
allowed_blank_lines   = 2
crlf                  = false
indent_string         = "    "
