[package]
name         = "key_parse"
version      = "0.1.1"
description  = "parse keymap like neovim"
license      = "Apache-2.0"
edition      = { workspace = true }
authors      = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde     = { workspace = true }
toml      = { workspace = true }
crossterm = { workspace = true }
miette    = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints]
workspace = true
