[package]
name    = "leetcode-api"
version = "0.1.0"
edition       = { workspace = true }
authors       = { workspace = true }
homepage      = { workspace = true }
repository    = { workspace = true }
rust-version  = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures    = { workspace = true }
tokio      = { workspace = true }
reqwest    = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }

miette  = { workspace = true }
regex   = { workspace = true }
tracing = { workspace = true }

tabled = { version = "^0.15" }

paste = { version = "^1" }

[lints]
workspace = true
