//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "moz_cookies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_name = "originAttributes")]
    pub origin_attributes: String,
    pub name: Option<String>,
    pub value: Option<String>,
    pub host: Option<String>,
    pub path: Option<String>,
    pub expiry: Option<i32>,
    #[sea_orm(column_name = "lastAccessed")]
    pub last_accessed: Option<i32>,
    #[sea_orm(column_name = "creationTime")]
    pub creation_time: Option<i32>,
    #[sea_orm(column_name = "isSecure")]
    pub is_secure: Option<i32>,
    #[sea_orm(column_name = "isHttpOnly")]
    pub is_http_only: Option<i32>,
    #[sea_orm(column_name = "inBrowserElement")]
    pub in_browser_element: Option<i32>,
    #[sea_orm(column_name = "sameSite")]
    pub same_site: Option<i32>,
    #[sea_orm(column_name = "rawSameSite")]
    pub raw_same_site: Option<i32>,
    #[sea_orm(column_name = "schemeMap")]
    pub scheme_map: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
