name: Clippy

on:
  push:

env:
  RUST_BACKTRACE: 1

jobs:
  clippy:
    name: Clippy rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [nightly]
    steps:
      - uses: actions/checkout/@v4

      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - name: Rust version
        if: ${{ ! startsWith(matrix.os, 'windows-') }}
        id: rustc-version
        run: |
          echo "rustc=$(rustc --version)" >> "$GITHUB_OUTPUT"
      - name: Rust Cache
        if: ${{ ! startsWith(matrix.os, 'windows-') }}
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-clippy-${{ steps.rustc-version.outputs.rustc }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Rust version
        if: ${{ startsWith(matrix.os, 'windows-') }}
        id: win-rustc-version
        run: echo "rustc=$(rustc --version)" >> ${env:GITHUB_OUTPUT}
      - name: Rust Cache
        if: ${{ startsWith(matrix.os, 'windows-') }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-clippy-${{ steps.win-rustc-version.outputs.rustc }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Dbus
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt update
          sudo apt install -y libdbus-1-dev pkg-config

      - name: Run Clippy Allow Warning
        if: ${{ ! (github.ref == 'refs/heads/main' || github.event_name == 'pull_request') }}
        run: cargo clippy --locked

      - name: Run Clippy Deny Warning
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        run: cargo clippy --locked -- -D warnings
