name: Clippy

on:
  push:

env:
  RUST_BACKTRACE: 1

jobs:
  clippy:
    name: Clippy rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout/@v4

      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: Install Dbus
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt update
          sudo apt install -y libdbus-1-dev pkg-config

      - name: Run Clippy Deny Warning
        run: cargo clippy --locked --all-targets  -- -D warnings
