name: Rustfmt

on: [push, pull_request, merge_group]

permissions:
  contents: write

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          # my rustfmt config use many nightly features
          toolchain: nightly
          components: rustfmt, cargo

      - name: Run fmt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: |
            fmt: with nightly rustfmt
        run: |
          cargo +nightly fmt --check --all
