name: lcode release

on:
    release:
        types:
            - published
            - prereleased

env:
    CARGO_TERM_COLOR: always

jobs:
    release:
        name: release ${{ matrix.target }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                target:
                    [
                        x86_64-unknown-linux-musl,
                        x86_64-pc-windows-gnu,
                        aarch64-apple-darwin,
                        x86_64-apple-darwin,
                    ]
        steps:
            - name: Checkout repository
              uses: actions/checkout@master

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Complie and release
              uses: rust-build/rust-build.action@v1.4.3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  RUSTTARGET: ${{ matrix.target }}
