name: Test

on: [push, pull_request, merge_group]

env:
  RUST_BACKTRACE: 1

jobs:
  # test:
  #   name: Test
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]
  #       rust: [stable]
  #   steps:
  #     - uses: actions/checkout/@v4
  #     - uses: dtolnay/rust-toolchain@master
  #       with:
  #         toolchain: nightly
  #     # - name: Install Dependencies
  #     #   if: startsWith(matrix.os, 'ubuntu-')
  #     #   run: |
  #     #     sudo apt update
  #     #     sudo apt install -y libdbus-1-dev libsecret-1-dev gnome-keyring
  #     - run: |
  #         cargo install cargo-nextest
  #         cargo nextest run

  clippy:
    name: Clippy rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [nightly]
    steps:
      - uses: actions/checkout/@v4
      - if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt update
          sudo apt install -y libdbus-1-dev pkg-config

      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy
      - run: cargo clippy -- -D warnings
